### ISSUE TITLE
`notifyIdeaCompilationStart` fails due to `java.nio.channels.OverlappingFileLockException`

### ISSUE THREAD

**Issue by guersam** [JetBrains/intellij-compiler-indices#1]
### Environment

- sbt: 1.10.0
- scala: 3.4.1
- sbt-idea-compiler-indices: 1.0.15

### Steps

1. Configure an sbt project using sbt shell for project reload and builds
2. Run the project using IntelliJ IDEA several times

### What is expected

It just runs 

### What actually happens

The compilation fails due to the failed `notifyIdeaCompilationStart`, caused by `OverlappingFileLockException`:

```
[IJ]last backend / Compile / notifyIdeaCompilationStart
[error] java.nio.channels.OverlappingFileLockException
[error] 	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
[error] 	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
[error] 	at java.base/sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1475)
[error] 	at java.base/java.nio.channels.FileChannel.lock(FileChannel.java:1240)
[error] 	at org.jetbrains.plugins.scala.indices.protocol.sbt.Locking$.lock(Locking.scala:23)
[error] 	at org.jetbrains.plugins.scala.indices.protocol.sbt.Locking$FileLockingExt$.lock$extension(Locking.scala:51)
[error] 	at org.jetbrains.sbt.indices.SbtIntellijIndicesPlugin$.$anonfun$perConfig$4(SbtIntellijIndicesPlugin.scala:63)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[error] (backend / Compile / notifyIdeaCompilationStart) java.nio.channels.OverlappingFileLockException
```

### Possible cause

Unlike the previous version ([source](https://github.com/JetBrains/intellij-compiler-indices/blob/v1.0.14/sbt-idea-compiler-indices/src/main/scala/org/jetbrains/sbt/indices/SbtIntellijIndicesPlugin.scala#L122-L125)), 1.0.15 doesn't seem to unlock the info dir unless there `notifyIdeaStart` fails. ([source](https://github.com/JetBrains/intellij-compiler-indices/blob/v1.0.15/sbt-idea-compiler-indices/src/main/scala/org/jetbrains/sbt/indices/SbtIntellijIndicesPlugin.scala#L63-L70)) 

/ping @vasilmkd

**Comment by vasilmkd** [comment]
Indeed, thank you for the help!

**Comment by vasilmkd** [comment]
https://youtrack.jetbrains.com/issue/SCL-22608/Deadlock-issue-in-IntelliJ-built-in-sbt-shell-when-usePipelining-is-enabled#focus=Comments-27-9979893.0-0
